// Generated by tools/import-halo-foley-audio.py. Original, unmodified Halo CE footsteps and Halo 3 Spartan vocals.
export const FOLEY_SOUNDS = {
  "footstep:ground": {
    "files": [
      "halo-foley/ce-cyborg-run_dirt1-4b7af4a1.wav",
      "halo-foley/ce-cyborg-run_dirt2-d68728c4.wav",
      "halo-foley/ce-cyborg-run_dirt3-29e2cd0e.wav",
      "halo-foley/ce-cyborg-run_dirt4-e00a3924.wav",
      "halo-foley/ce-cyborg-run_dirt5-65d323d2.wav",
      "halo-foley/ce-cyborg-run_dirt6-43383437.wav",
      "halo-foley/ce-cyborg-run_grass1-fe2ee546.wav",
      "halo-foley/ce-cyborg-run_grass2-0a138205.wav",
      "halo-foley/ce-cyborg-run_grass3-7bb5237d.wav",
      "halo-foley/ce-cyborg-run_grass4-bb3778e8.wav",
      "halo-foley/ce-cyborg-run_grass5-f97e514c.wav",
      "halo-foley/ce-cyborg-run_grass6-8b3f531f.wav"
    ],
    "gain": 0.858,
    "variation": 0
  },
  "footstep:sand": {
    "files": [
      "halo-foley/ce-cyborg-run_snow1-3bd23bf2.wav",
      "halo-foley/ce-cyborg-run_snow2-f96ab5f6.wav",
      "halo-foley/ce-cyborg-run_snow3-d05665e9.wav",
      "halo-foley/ce-cyborg-run_snow4-247ea69a.wav",
      "halo-foley/ce-cyborg-run_snow5-f0334560.wav",
      "halo-foley/ce-cyborg-run_snow6-308f6c1d.wav"
    ],
    "gain": 0.845,
    "variation": 0
  },
  "footstep:metal": {
    "files": [
      "halo-foley/ce-cyborg-run_grating1-a0dbf44e.wav",
      "halo-foley/ce-cyborg-run_grating2-5024b886.wav",
      "halo-foley/ce-cyborg-run_grating3-aed38bc7.wav",
      "halo-foley/ce-cyborg-run_grating4-0c4f004c.wav",
      "halo-foley/ce-cyborg-run_grating5-82cc4b62.wav",
      "halo-foley/ce-cyborg-run_grating6-f29dd511.wav"
    ],
    "gain": 0.666,
    "variation": 0
  },
  "footstep:stone": {
    "files": [
      "halo-foley/ce-cyborg-run_grtcement1-383ea904.wav",
      "halo-foley/ce-cyborg-run_grtcement2-65298607.wav",
      "halo-foley/ce-cyborg-run_grtcement3-3a6186de.wav",
      "halo-foley/ce-cyborg-run_grtcement4-8b931f19.wav",
      "halo-foley/ce-cyborg-run_grtcement5-444a6ec9.wav",
      "halo-foley/ce-cyborg-run_grtcement6-af4bffce.wav"
    ],
    "gain": 0.928,
    "variation": 0
  },
  "footstep:wood": {
    "files": [
      "halo-foley/ce-cyborg-run_wood1-638b7d3d.wav",
      "halo-foley/ce-cyborg-run_wood2-d5399d3c.wav",
      "halo-foley/ce-cyborg-run_wood3-0c2ad4d7.wav",
      "halo-foley/ce-cyborg-run_wood4-3d00c6b3.wav",
      "halo-foley/ce-cyborg-run_wood5-d02cd6af.wav",
      "halo-foley/ce-cyborg-run_wood6-bd639952.wav"
    ],
    "gain": 0.828,
    "variation": 0
  },
  "footstep:water": {
    "files": [
      "halo-foley/ce-cyborg-run_water1-a295e8a4.wav",
      "halo-foley/ce-cyborg-run_water2-a4742581.wav",
      "halo-foley/ce-cyborg-run_water3-76878610.wav",
      "halo-foley/ce-cyborg-walk_water1-707809a7.wav",
      "halo-foley/ce-cyborg-walk_water2-d11ab498.wav",
      "halo-foley/ce-cyborg-walk_water3-aa57f9b2.wav",
      "halo-foley/ce-cyborg-walk_water4-15aac008.wav",
      "halo-foley/ce-cyborg-walk_water5-98395858.wav"
    ],
    "gain": 0.629,
    "variation": 0
  },
  "land:ground": {
    "files": [
      "halo-foley/ce-cyborg-jump_dirt1-c47deb06.wav",
      "halo-foley/ce-cyborg-jump_dirt2-f465cd68.wav",
      "halo-foley/ce-cyborg-jump_dirt3-537ade5c.wav"
    ],
    "gain": 0.965,
    "variation": 0
  },
  "land:sand": {
    "files": [
      "halo-foley/ce-cyborg-jump_snow1-ac9a2b0b.wav",
      "halo-foley/ce-cyborg-jump_snow2-6801936f.wav",
      "halo-foley/ce-cyborg-jump_snow3-0ee4647b.wav"
    ],
    "gain": 0.891,
    "variation": 0
  },
  "land:metal": {
    "files": [
      "halo-foley/ce-cyborg-jump_grating1-5adda2c3.wav",
      "halo-foley/ce-cyborg-jump_grating2-7b44c1c4.wav",
      "halo-foley/ce-cyborg-jump_grating3-8fd03196.wav"
    ],
    "gain": 0.661,
    "variation": 0
  },
  "land:stone": {
    "files": [
      "halo-foley/ce-cyborg-jump_grtcement1-7453d39d.wav",
      "halo-foley/ce-cyborg-jump_grtcement2-3570e1c5.wav",
      "halo-foley/ce-cyborg-jump_grtcement3-8bee0e5a.wav"
    ],
    "gain": 0.973,
    "variation": 0
  },
  "land:wood": {
    "files": [
      "halo-foley/ce-cyborg-jump_wood1-6e4c4c54.wav",
      "halo-foley/ce-cyborg-jump_wood2-2632b02f.wav",
      "halo-foley/ce-cyborg-jump_wood3-9fed4764.wav"
    ],
    "gain": 1.8,
    "variation": 0
  },
  "land:water": {
    "files": [
      "halo-foley/ce-cyborg-jump_water1-ababd5b3.wav",
      "halo-foley/ce-cyborg-jump_water2-707b5aba.wav",
      "halo-foley/ce-cyborg-jump_water3-f8717c4a.wav"
    ],
    "gain": 0.857,
    "variation": 0
  },
  "land-hard": {
    "files": [
      "halo-foley/ce-cyborg-generic_jump1-448a7740.wav",
      "halo-foley/ce-cyborg-generic_jump2-524156c1.wav",
      "halo-foley/ce-cyborg-generic_jump3-58ac641c.wav"
    ],
    "gain": 0.842,
    "variation": 0
  },
  "voice:hurt": {
    "files": [
      "halo-foley/h3-chief-combat-voices-pain1-15d23b9b.wav",
      "halo-foley/h3-chief-combat-voices-pain2-175905da.wav",
      "halo-foley/h3-chief-combat-voices-pain3-d69d870f.wav",
      "halo-foley/h3-chief-combat-voices-pain8-a1593e15.wav",
      "halo-foley/h3-chief-combat-voices-pain28-406e786c.wav"
    ],
    "gain": 1.16,
    "variation": 0
  },
  "voice:hurt-heavy": {
    "files": [
      "halo-foley/h3-chief-combat-voices-pain7-0e9b51fb.wav",
      "halo-foley/h3-chief-combat-voices-pain12-9d403f34.wav",
      "halo-foley/h3-chief-combat-voices-pain20-b5720581.wav",
      "halo-foley/h3-chief-combat-voices-pain24-6fe8a787.wav",
      "halo-foley/h3-chief-combat-voices-pain26-a3e9b634.wav"
    ],
    "gain": 1.003,
    "variation": 0
  },
  "voice:shield-break": {
    "files": [
      "halo-foley/h3-chief-combat-voices-pain27-314dcfb0.wav",
      "halo-foley/h3-chief-combat-voices-pain34-4951fce7.wav",
      "halo-foley/h3-chief-combat-voices-pain36-ca28a603.wav",
      "halo-foley/h3-chief-combat-voices-pain39-cdb37f93.wav"
    ],
    "gain": 1.549,
    "variation": 0
  },
  "voice:death": {
    "files": [
      "halo-foley/h3-chief-combat-voices-death9-d6f87a10.wav",
      "halo-foley/h3-chief-combat-voices-death10-ff518082.wav",
      "halo-foley/h3-chief-combat-voices-death11-6b986f38.wav",
      "halo-foley/h3-chief-combat-voices-death12-489018f1.wav",
      "halo-foley/h3-chief-combat-voices-death18-e859f130.wav",
      "halo-foley/h3-chief-combat-voices-death26-03b668d3.wav"
    ],
    "gain": 1.081,
    "variation": 0
  }
} as const
