// Generated by tools/import-halo3-grenade-audio.py. Original, unmodified Halo 3 recordings.
export const GRENADE_SOUNDS = {
  "grenade-bounce:frag:stone": {
    "files": [
      "halo3-grenades/frag-stone-1.wav",
      "halo3-grenades/frag-stone-2.wav",
      "halo3-grenades/frag-stone-3.wav"
    ],
    "gain": 0.85,
    "variation": 0
  },
  "grenade-bounce:frag:dirt": {
    "files": [
      "halo3-grenades/frag-dirt-1.wav",
      "halo3-grenades/frag-dirt-2.wav",
      "halo3-grenades/frag-dirt-3.wav"
    ],
    "gain": 0.85,
    "variation": 0
  },
  "grenade-bounce:plasma:stone": {
    "files": [
      "halo3-grenades/plasma-stone-1.wav",
      "halo3-grenades/plasma-stone-2.wav",
      "halo3-grenades/plasma-stone-3.wav"
    ],
    "gain": 0.85,
    "variation": 0
  }
} as const
