// Generated by tools/import-halo2-dual-audio.py.
export const HALO2_SOUNDS = {
  "smg": {
    "files": [
      "halo2-dual/smg-cefe012e300c.wav",
      "halo2-dual/smg-3063b7be7b22.wav",
      "halo2-dual/smg-6bcc30e68efe.wav",
      "halo2-dual/smg-da452a4bb3f9.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "smg:reload": {
    "files": [
      "halo2-dual/smg-d2301aac359f.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "smg:reload-empty": {
    "files": [
      "halo2-dual/smg-fe7a97bd7fce.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "melee:smg": {
    "files": [
      "halo2-dual/smg-b093fceacf43.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "plasma-pistol": {
    "files": [
      "halo2-dual/pp-87a3a35c5e0d.wav",
      "halo2-dual/pp-e142de1ca34d.wav",
      "halo2-dual/pp-7680d510df78.wav",
      "halo2-dual/pp-92391f6f6181.wav",
      "halo2-dual/pp-077dd4165f20.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "plasma-pistol:charge-start": {
    "files": [
      "halo2-dual/pp-b0f44adac435.wav"
    ],
    "gain": 0.65,
    "variation": 0
  },
  "plasma-pistol:charge-loop": {
    "files": [
      "halo2-dual/pp-2f08509e0ed0.wav"
    ],
    "gain": 0.5,
    "variation": 0
  },
  "plasma-pistol:charged": {
    "files": [
      "halo2-dual/pp-76683e368206.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "plasma-pistol:charged-hit": {
    "files": [
      "halo2-dual/pp-175dd2df7b08.wav",
      "halo2-dual/pp-af91f34b7319.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "plasma-pistol:vent": {
    "files": [
      "halo2-dual/pp-cfa76bfb8f34.wav"
    ],
    "gain": 0.55,
    "variation": 0
  },
  "melee:plasma-pistol": {
    "files": [
      "halo2-dual/pp-e8dafd587cef.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "plasma-rifle": {
    "files": [
      "halo2-dual/pr-8d86defca813.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "melee:plasma-rifle": {
    "files": [
      "halo2-dual/pr-f5d5f39b9313.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "needler": {
    "files": [
      "halo2-dual/needler-ce7dbad39a5d.wav",
      "halo2-dual/needler-1d6e7fe6d87c.wav",
      "halo2-dual/needler-091b9bfba521.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "needler:reload": {
    "files": [
      "halo2-dual/needler-d5b6476ba613.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "melee:needler": {
    "files": [
      "halo2-dual/needler-0e39daa6049f.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "supercombine": {
    "files": [
      "halo2-dual/needler-2236fe365569.wav"
    ],
    "gain": 1,
    "variation": 0
  }
} as const
