// Generated by tools/import-halo-audio.py. Do not hand-edit.
export const HALO_SOUNDS = {
  "assault-rifle": {
    "files": [
      "halo-original/ce-assault_rifle_fire_brown2_1-8a04084ac7.wav",
      "halo-original/ce-assault_rifle_fire_brown2_2-9099c36f8a.wav",
      "halo-original/ce-assault_rifle_fire_brown2_3-9c360d2887.wav",
      "halo-original/ce-assault_rifle_fire_brown2_5-b03931f5e9.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "magnum": {
    "files": [
      "halo-original/ce-pistol_fire_handgun2-504e583853.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "sniper": {
    "files": [
      "halo-original/ce-sniper_rifle_fire_ruger21-ee0e8b184a.wav",
      "halo-original/ce-sniper_rifle_fire_ruger22-65eea38586.wav",
      "halo-original/ce-sniper_rifle_fire_ruger23-9f191d6173.wav",
      "halo-original/ce-sniper_rifle_fire_ruger24-b89a6cc3ec.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "shotgun": {
    "files": [
      "halo-original/ce-shotgun_fire_shotgun6050-5d39a030f8.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "rocket-launcher": {
    "files": [
      "halo-original/ce-rocket_launcher_fire_rocket15-1a8e4723a1.wav",
      "halo-original/ce-rocket_launcher_fire_rocket16-1e76ca7c59.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "warthog": {
    "files": [
      "halo-original/ce-chaingun_fire_m60_1-95a61ef20d.wav",
      "halo-original/ce-chaingun_fire_m60_3-ca614f4b81.wav",
      "halo-original/ce-chaingun_fire_m60_4-feb8abf3d9.wav",
      "halo-original/ce-chaingun_fire_m60_6-02854ddf1b.wav",
      "halo-original/ce-chaingun_fire_m60_9-7b8087608a.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "melee:assault-rifle": {
    "files": [
      "halo-original/ce-ar_melee-4fd9dac3cd.wav",
      "halo-original/ce-ar_melee_ar_melee_2-470e701520.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "melee:magnum": {
    "files": [
      "halo-original/ce-pistol_melee-46fd8e1b83.wav",
      "halo-original/ce-pistol_melee_pistol_melee_2-4a4306a6c0.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "melee:sniper": {
    "files": [
      "halo-original/ce-sniper_melee-f801344233.wav",
      "halo-original/ce-sniper_melee_sniper_melee_2-364ab22764.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "melee:shotgun": {
    "files": [
      "halo-original/ce-shotgun_melee-bf08ca1f2e.wav",
      "halo-original/ce-shotgun_melee_shotgun_melee_2-c9a9b0d7da.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "melee:rocket-launcher": {
    "files": [
      "halo-original/ce-rocket_melee-3c33383aa4.wav",
      "halo-original/ce-rocket_melee_rocket_melee_2-49745bf3df.wav",
      "halo-original/ce-rocket_melee_rocket_melee_3-a1e65fb0f4.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "assault-rifle:reload": {
    "files": [
      "halo-original/ce-ar_reload-d68d3b5ed4.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "magnum:reload": {
    "files": [
      "halo-original/ce-pistol_reload_pistolreload-d9a8328257.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "sniper:reload": {
    "files": [
      "halo-original/ce-sniper_reload_full-ee645b2433.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "rocket-launcher:reload": {
    "files": [
      "halo-original/ce-rocket_reload_f-0a5686cef0.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "sniper:reload-empty": {
    "files": [
      "halo-original/ce-sniper_reload_empty-537b8ffa74.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "rocket-launcher:reload-empty": {
    "files": [
      "halo-original/ce-rocket_reload_e-4b2faeb50d.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "shotgun:in": {
    "files": [
      "halo-original/ce-shotgun_reload2_1-0679d4f8f9.wav",
      "halo-original/ce-shotgun_reload2_1_shotgun_reload2_2-c0925549bd.wav",
      "halo-original/ce-shotgun_reload2_1_shotgun_reload2_3-cf92a4bfd1.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "shotgun:open": {
    "files": [
      "halo-original/ce-shotgun_reload1_1-828b837be6.wav",
      "halo-original/ce-shotgun_reload1_1_shotgun_reload1_2-ef23194bd0.wav",
      "halo-original/ce-shotgun_reload1_1_shotgun_reload1_3-916cb7f255.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "shotgun:close": {
    "files": [
      "halo-original/ce-shotgun_reload3-53d6f5f31c.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "shotgun-pump": {
    "files": [
      "halo-original/ce-shotgun_fire-9e7c87c976.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "body-hit": {
    "files": [
      "halo-original/halo3-impacts-bullet_impact_vest1-3ba4f1f8a.wav",
      "halo-original/halo3-impacts-bullet_impact_vest2-dfad8ca022.wav",
      "halo-original/halo3-impacts-bullet_impact_vest3-80390f2455.wav",
      "halo-original/halo3-impacts-bullet_impact_vest4-81b73bf2b8.wav",
      "halo-original/halo3-impacts-bullet_impact_vest5-abfb6ffd33.wav"
    ],
    "gain": 0.86,
    "variation": 0
  },
  "halo3-armor-hit": {
    "files": [
      "halo-original/halo3-impacts-bullet_impact_vest1-3ba4f1f8a.wav",
      "halo-original/halo3-impacts-bullet_impact_vest2-dfad8ca022.wav",
      "halo-original/halo3-impacts-bullet_impact_vest3-80390f2455.wav",
      "halo-original/halo3-impacts-bullet_impact_vest4-81b73bf2b8.wav",
      "halo-original/halo3-impacts-bullet_impact_vest5-abfb6ffd33.wav"
    ],
    "gain": 0.86,
    "variation": 0
  },
  "shield-hit": {
    "files": [
      "halo-original/halo3-impacts-bullet_impact_vest1-3ba4f1f8a.wav",
      "halo-original/halo3-impacts-bullet_impact_vest2-dfad8ca022.wav",
      "halo-original/halo3-impacts-bullet_impact_vest3-80390f2455.wav",
      "halo-original/halo3-impacts-bullet_impact_vest4-81b73bf2b8.wav",
      "halo-original/halo3-impacts-bullet_impact_vest5-abfb6ffd33.wav"
    ],
    "gain": 0.86,
    "variation": 0
  },
  "melee-impact:assault-rifle": {
    "files": [
      "halo-original/halo3-impacts-bullet_impact_vest1-3ba4f1f8a.wav",
      "halo-original/halo3-impacts-bullet_impact_vest2-dfad8ca022.wav",
      "halo-original/halo3-impacts-bullet_impact_vest3-80390f2455.wav",
      "halo-original/halo3-impacts-bullet_impact_vest4-81b73bf2b8.wav",
      "halo-original/halo3-impacts-bullet_impact_vest5-abfb6ffd33.wav"
    ],
    "gain": 0.86,
    "variation": 0
  },
  "melee-impact:magnum": {
    "files": [
      "halo-original/halo3-impacts-bullet_impact_vest1-3ba4f1f8a.wav",
      "halo-original/halo3-impacts-bullet_impact_vest2-dfad8ca022.wav",
      "halo-original/halo3-impacts-bullet_impact_vest3-80390f2455.wav",
      "halo-original/halo3-impacts-bullet_impact_vest4-81b73bf2b8.wav",
      "halo-original/halo3-impacts-bullet_impact_vest5-abfb6ffd33.wav"
    ],
    "gain": 0.86,
    "variation": 0
  },
  "melee-impact:sniper": {
    "files": [
      "halo-original/halo3-impacts-bullet_impact_vest1-3ba4f1f8a.wav",
      "halo-original/halo3-impacts-bullet_impact_vest2-dfad8ca022.wav",
      "halo-original/halo3-impacts-bullet_impact_vest3-80390f2455.wav",
      "halo-original/halo3-impacts-bullet_impact_vest4-81b73bf2b8.wav",
      "halo-original/halo3-impacts-bullet_impact_vest5-abfb6ffd33.wav"
    ],
    "gain": 0.86,
    "variation": 0
  },
  "melee-impact:shotgun": {
    "files": [
      "halo-original/halo3-impacts-bullet_impact_vest1-3ba4f1f8a.wav",
      "halo-original/halo3-impacts-bullet_impact_vest2-dfad8ca022.wav",
      "halo-original/halo3-impacts-bullet_impact_vest3-80390f2455.wav",
      "halo-original/halo3-impacts-bullet_impact_vest4-81b73bf2b8.wav",
      "halo-original/halo3-impacts-bullet_impact_vest5-abfb6ffd33.wav"
    ],
    "gain": 0.86,
    "variation": 0
  },
  "melee-impact:rocket-launcher": {
    "files": [
      "halo-original/halo3-impacts-bullet_impact_vest1-3ba4f1f8a.wav",
      "halo-original/halo3-impacts-bullet_impact_vest2-dfad8ca022.wav",
      "halo-original/halo3-impacts-bullet_impact_vest3-80390f2455.wav",
      "halo-original/halo3-impacts-bullet_impact_vest4-81b73bf2b8.wav",
      "halo-original/halo3-impacts-bullet_impact_vest5-abfb6ffd33.wav"
    ],
    "gain": 0.86,
    "variation": 0
  },
  "melee-impact:battle-rifle": {
    "files": [
      "halo-original/halo3-impacts-bullet_impact_vest1-3ba4f1f8a.wav",
      "halo-original/halo3-impacts-bullet_impact_vest2-dfad8ca022.wav",
      "halo-original/halo3-impacts-bullet_impact_vest3-80390f2455.wav",
      "halo-original/halo3-impacts-bullet_impact_vest4-81b73bf2b8.wav",
      "halo-original/halo3-impacts-bullet_impact_vest5-abfb6ffd33.wav"
    ],
    "gain": 0.86,
    "variation": 0
  },
  "melee-impact:needler": {
    "files": [
      "halo-original/halo3-impacts-bullet_impact_vest1-3ba4f1f8a.wav",
      "halo-original/halo3-impacts-bullet_impact_vest2-dfad8ca022.wav",
      "halo-original/halo3-impacts-bullet_impact_vest3-80390f2455.wav",
      "halo-original/halo3-impacts-bullet_impact_vest4-81b73bf2b8.wav",
      "halo-original/halo3-impacts-bullet_impact_vest5-abfb6ffd33.wav"
    ],
    "gain": 0.86,
    "variation": 0
  },
  "battle-rifle": {
    "files": [
      "halo-original/battle-rifle-battle_rifle_fire2-93e04b4cec.wav",
      "halo-original/battle-rifle-battle_rifle_fire3-c9154d637c.wav",
      "halo-original/battle-rifle-battle_rifle_fire4-10d4e53fb6.wav",
      "halo-original/battle-rifle-battle_rifle_fire5-a5e29b7691.wav",
      "halo-original/battle-rifle-battle_rifle_fire6-44e0379a1f.wav",
      "halo-original/battle-rifle-battle_rifle_fire7-5a7547b3ac.wav",
      "halo-original/battle-rifle-battle_rifle_fire8-82201b9cac.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "melee:battle-rifle": {
    "files": [
      "halo-original/battle-rifle-br_melee1a-3140ddba37.wav",
      "halo-original/battle-rifle-br_melee1b-c63caa0f82.wav",
      "halo-original/battle-rifle-br_melee1c-edeea11108.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "battle-rifle:reload": {
    "files": [
      "halo-original/battle-rifle-br_reload_full1-899930e39b.wav",
      "halo-original/battle-rifle-br_reload_full2-1c109712b3.wav",
      "halo-original/battle-rifle-br_reload_full3-ecb4386284.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "battle-rifle:reload-empty": {
    "files": [
      "halo-original/battle-rifle-br_reload_empty1-0dba37c325.wav",
      "halo-original/battle-rifle-br_reload_empty2-323136ae89.wav",
      "halo-original/battle-rifle-br_reload_empty3-6f24c5c71d.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "battle-rifle:zoom-in": {
    "files": [
      "halo-original/battle-rifle-battle_rifle_zoom_in-5eec5cfc0e.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "battle-rifle:zoom-out": {
    "files": [
      "halo-original/battle-rifle-battle_rifle_zoom_out-ee0758ff4b.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "needler": {
    "files": [
      "halo-original/needler-needlefire11-b163ee182b.wav",
      "halo-original/needler-needlefire12-3479089401.wav",
      "halo-original/needler-needlefire13-49884370ce.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "needler:reload": {
    "files": [
      "halo-original/needler-needler_reload_full_1-72798f346f.wav",
      "halo-original/needler-needler_reload_full_2-f96bd0cd3e.wav",
      "halo-original/needler-needler_reload_full_3-0dfdadabc3.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "melee:needler": {
    "files": [
      "halo-original/needler-needler_melee_1-483626c01a.wav",
      "halo-original/needler-needler_melee_2-35af4a18ac.wav",
      "halo-original/needler-needler_melee_3-e25eb06b79.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "supercombine": {
    "files": [
      "halo-original/needler-needler_super_expl-63abc5279f.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "energy-sword": {
    "files": [
      "halo-original/energy-sword-melee_1-b0fa1ccfd1.wav",
      "halo-original/energy-sword-melee_1b-32c8f8b959.wav",
      "halo-original/energy-sword-melee_1c-9a261df04e.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "melee:energy-sword": {
    "files": [
      "halo-original/energy-sword-melee_1-b0fa1ccfd1.wav",
      "halo-original/energy-sword-melee_1b-32c8f8b959.wav",
      "halo-original/energy-sword-melee_1c-9a261df04e.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "sword-impact": {
    "files": [
      "halo-original/energy-sword-sword_hit_char1-36d6ba8f9c.wav",
      "halo-original/energy-sword-sword_hit_char2-4875ef71be.wav",
      "halo-original/energy-sword-sword_hit_char3-8fbed9840b.wav",
      "halo-original/energy-sword-sword_hit_char4-b258a41bb8.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "melee-impact:energy-sword": {
    "files": [
      "halo-original/energy-sword-sword_hit_char1-36d6ba8f9c.wav",
      "halo-original/energy-sword-sword_hit_char2-4875ef71be.wav",
      "halo-original/energy-sword-sword_hit_char3-8fbed9840b.wav",
      "halo-original/energy-sword-sword_hit_char4-b258a41bb8.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "gravity-hammer": {
    "files": [
      "halo-original/gravity-hammer-hammer_hit1-5de9c7306e.wav",
      "halo-original/gravity-hammer-hammer_hit2-5e3e88fb0b.wav",
      "halo-original/gravity-hammer-hammer_hit3-4761f22f01.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "hammer-windup": {
    "files": [
      "halo-original/gravity-hammer-hammer_melee1-5d26ffcfb7.wav",
      "halo-original/gravity-hammer-hammer_melee2-d1cedc0160.wav",
      "halo-original/gravity-hammer-hammer_melee3-3531a3542b.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "melee:gravity-hammer": {
    "files": [
      "halo-original/gravity-hammer-hammer_melee1-5d26ffcfb7.wav",
      "halo-original/gravity-hammer-hammer_melee2-d1cedc0160.wav",
      "halo-original/gravity-hammer-hammer_melee3-3531a3542b.wav"
    ],
    "gain": 1,
    "variation": 0
  },
  "melee-impact:gravity-hammer": {
    "files": [
      "halo-original/gravity-hammer-hammer_hit1-5de9c7306e.wav",
      "halo-original/gravity-hammer-hammer_hit2-5e3e88fb0b.wav",
      "halo-original/gravity-hammer-hammer_hit3-4761f22f01.wav"
    ],
    "gain": 1,
    "variation": 0
  }
}
