// Generated by tools/import-halo3-vehicle-audio.py. Original, unmodified Halo 3 recordings.
export const VEHICLE_SOUNDS = {
  "ghost": {
    "files": [
      "halo3-vehicles/ghost.wav"
    ],
    "gain": 1.0,
    "variation": 0
  },
  "banshee": {
    "files": [
      "halo3-vehicles/banshee-1.wav",
      "halo3-vehicles/banshee-2.wav",
      "halo3-vehicles/banshee-3.wav"
    ],
    "gain": 0.72,
    "variation": 0
  },
  "fuel-rod": {
    "files": [
      "halo3-vehicles/fuel-rod-1.wav",
      "halo3-vehicles/fuel-rod-2.wav",
      "halo3-vehicles/fuel-rod-3.wav"
    ],
    "gain": 0.8,
    "variation": 0
  },
  "fuel-rod-explosion": {
    "files": [
      "halo3-vehicles/fuel-rod-explosion-1.wav",
      "halo3-vehicles/fuel-rod-explosion-2.wav",
      "halo3-vehicles/fuel-rod-explosion-3.wav",
      "halo3-vehicles/fuel-rod-explosion-4.wav"
    ],
    "gain": 0.85,
    "variation": 0
  },
  "ghost-engine": {
    "files": [
      "halo3-vehicles/ghost-engine.wav"
    ],
    "gain": 2.311,
    "variation": 0
  },
  "ghost-boost": {
    "files": [
      "halo3-vehicles/ghost-boost.wav"
    ],
    "gain": 0.9,
    "variation": 0
  },
  "banshee-engine": {
    "files": [
      "halo3-vehicles/banshee-engine.wav"
    ],
    "gain": 1.21,
    "variation": 0
  },
  "banshee-contrail": {
    "files": [
      "halo3-vehicles/banshee-contrail.wav"
    ],
    "gain": 1.32,
    "variation": 0
  }
} as const
